name: Maintainers approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  maintainer-approved-check:
    name: Minimum approval count
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - id: find-maintainers
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            // Get the collaborators - filtered to maintainer permissions
            const maintainersResponse = await github.request('GET /repos/{owner}/{repo}/collaborators', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                permission: 'maintain',
                affiliation: 'all',
                per_page: 100
            });

            return maintainersResponse.data.map(item => item.login).join(', ');

      - uses: peternied/required-approval@eff43cda336a39896fd03966642576193eb41550 # v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-required: 1
          required-approvers-list: ${{ steps.find-maintainers.outputs.result }}
