name: Pull Request Checks

on:
  pull_request:
    types:
      [
        opened,
        edited,
        review_requested,
        synchronize,
        reopened,
        ready_for_review,
      ]

jobs:
  verify-description-checklist:
    name: Verify Description Checklist
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: peternied/check-pull-request-description-checklist@d120563ef866fe677b7da9f9930ceb9279d81a9f # v1
        with:
          checklist-items: |
            New functionality includes testing.
            All tests pass
            New functionality has been documented.
            New functionality has javadoc added
            Commits are signed per the DCO using --signoff
            Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
