name: Auto triage based on the component label in issue

on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  apply-label:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const { issue, repository } = context.payload;
            const { number, body } = issue;
            const { owner, name } = repository;
            const regex = /###\sRelated\scomponent\n\n(\w.*)\n/gm;
            let match;
            while ( ( match = regex.exec( body ) ) ) {
              const [ , component_label ] = match;
              await github.rest.issues.addLabels( {
                owner: owner.login,
                repo: name,
                issue_number: number,
                labels: [ `${ component_label }` ],
              } );
            }
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['untriaged']
            })
