name: Validate Gradle Wrapper
on: [pull_request]

jobs:
  validate:
    name: Validate
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: step-security/gradle-actions/wrapper-validation@c2d874d5f9d267a85a1b5829c6b5a569e33e05c8 # v5.0.0
